# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'windows-2019'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: 'python -m pip install --upgrade pip && pip install -r requirements.txt'
  displayName: "install required packages"

- task: CmdLine@2
  inputs:
    script: 'python.exe src/winzog.py'
  displayName: 'test run Winzog?'

- task: CmdLine@2
  inputs:
    script: './makeInstaller http://devurl/'
  displayName: 'build dev package'

- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: './dist/winzog.exe'
    artifactName: DevPackage

- task: CmdLine@2
  inputs:
    script: './makeInstaller http://produrl/'
  displayName: 'build production package'

- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: './dist/winzog.exe'
    artifactName: ProdPackage

