# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'windows-2019'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: 'python -m pip install --upgrade pip
pip install -r requirements.txt'
  displayName: "install required packages"

- task: CmdLine@2
  inputs:
    script: 'python.exe winzog.py'
  displayName: 'test run Winzog?'

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: 'python.exe winzog.py'